---
author:
  - 'Mike Tonks <miket@cpan.org>'
build_requires:
  DBD::SQLite: 0
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Foo
no_index:
  directory:
    - inc
    - t
requires:
  DBI: 0
  Exporter: 0
  Log::Any: 0
  Tie::IxHash: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03_1
